### ISSUE TITLE
Next Auth Fails when trying to log in with Google

### ISSUE THREAD

**Issue by spykelionel** [OpenSoftwareMovement/language_crowdsource#1]
Next Authentication fails while trying to login with Google Identity Provider.

When I select Log in with Google, it displays the error below
![image](https://github.com/OpenSoftwareMovement/language_crowdsource/assets/59184392/9a324c89-c52e-4a69-998b-d4e6aa149aa9)

- I have enabled Google on the list of Providers on Strapi dashboard.
- I have also added Google credentials i.e. ```GOOGLE_CLIENT_SECRET``` and ```GOOGLE_CLIENT_SECRET```

The error stack:
```
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error fetch failed {
  message: 'fetch failed',
  stack: 'TypeError: fetch failed\n' +
    '    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Object.jwt (webpack-internal:///(api)/./pages/api/auth/[...nextauth].ts:33:34)\n' +
    '    at async Object.callback (/home/spyke/Desktop/project/terminativ/lcs/frontend/node_modules/next-auth/core/routes/callback.js:133:25)\n' +
    '    at async NextAuthHandler (/home/spyke/Desktop/project/terminativ/lcs/frontend/node_modules/next-auth/core/index.js:201:28)\n' +
    '    at async NextAuthNextHandler (/home/spyke/Desktop/project/terminativ/lcs/frontend/node_modules/next-auth/next/index.js:23:19)\n' +
    '    at async Object.apiResolver (/home/spyke/Desktop/project/terminativ/lcs/frontend/node_modules/next/dist/server/api-utils/node.js:184:9)\n' +
    '    at async DevServer.runApi (/home/spyke/Desktop/project/terminativ/lcs/frontend/node_modules/next/dist/server/next-server.js:403:9)\n' +
    '    at async Object.fn (/home/spyke/Desktop/project/terminativ/lcs/frontend/node_modules/next/dist/server/base-server.js:493:37)\n' +
    '    at async Router.execute (/home/spyke/Desktop/project/terminativ/lcs/frontend/node_modules/next/dist/server/router.js:222:36)',
  name: 'TypeError'
}


```

**Comment by spykelionel** [comment]
@giftcup
